### ISSUE TITLE
BsMax for Blender 2.80 - 3.1 - error report

### ISSUE THREAD

**Issue by yoyojoeGH** [NevilArt/BsMax_2_80#23]
Hi !,
Today I've attempted to use version 0.1.0.20211128 - but am unable to run this Blender add-on, error report reads:-

Traceback (most recent call last):
 File "D:\Blender300\3.0\scripts\modules\addon_utils.py" line 351, in enable
   mod=_import_(module_name)
File "C:\Users\Dave\AppData\Roaming\Blender Foundation\Blender\3.0\scripts\addons\BsMax_2_80-master\_init_.py".line 41, in <module>
  from .keymaps import register_keymaps, unregister_keymaps
ImportError: cannot import name 'register_keymaps' from 'BsMax_2_80-master.keymaps' (unknown location)

fyi - I'm not sure what that all means but I've tried to accurately copy out the error report exactly as it appeared, my laptop is running Win 10 and successfully installed other Blender add-ons today.  I hope the above is helpful to you.

regards and best wishes,

yoyojoe

**Comment by NevilArt** [comment]
Hi Dear  Yoyojoe

Did you Install the zip file that you downloaded or extracted before install?

Open Blender
File menu/ Defaults / Load factory setting

And then fallow Installation steps

Download all the package as zip file.
Go to Preferences > Add-ons > Install.
Select the ".Zip" file that you downloaded.
Select the Software you use to use.
Press the "Save Preferences Setting" button.
It is better to restart the Blender after install.
Note: Some times need to reset factory the blender to make add-on work fine (happens when add-ons install to alpha version).

Then let me know that problem solved or not.
Thank you for report.
