### ISSUE TITLE
Wrong Maya zoom navigation.

### ISSUE THREAD

**Issue by WalterMPatrick** [NevilArt/BsMax_2_80#6]
Maya zoom navigation is alt(option for mac)+RM and sliding mouse horizontally. In the plugin, it's set to vertical.

**Comment by NevilArt** [comment]
I just assign the Maya short keys to blender default navigation operator and this that works on vertical movement only. I had to write a new zoom operator. it wont be easy to finish it tonight because zooming step had to change by distance of view to focal point, but I hope this weekend I be able to fix it. 

Thank you for report the issue.

**Comment by WalterMPatrick** [comment]
Thanks! You are great!

**Comment by NevilArt** [comment]
Finlay I found a very simple way to fix this issue. Blender it self has this ability to zoom in horizontal mouse movement. now if you select the 'Maya' navigation in 'BsMax' the Zoom mode automatically will set to Horizontal mode.

**Comment by WalterMPatrick** [comment]
Thank you so much! Your'e amazing!

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐
